### ISSUE TITLE
 undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by joowh85** [glebm/i18n-tasks#122]
After 'i18n-tasks translate-missing' command, occours error.

How can I fix this?

Here is full stacktrace.

```
/home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:90:in `next': undefined method `each' for nil:NilClass (NoMethodError)
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:90:in `parse_value'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:88:in `block in parse_value'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:88:in `map'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:88:in `parse_value'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:63:in `from_values'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:36:in `fetch_google_translations'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:27:in `block in google_translate_list'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:26:in `each'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:26:in `map'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:26:in `google_translate_list'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:13:in `block in google_translate_forest'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/data/tree/nodes.rb:13:in `each'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/data/tree/nodes.rb:13:in `each'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:12:in `inject'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/google_translation.rb:12:in `google_translate_forest'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/command/commands/missing.rb:29:in `translate_missing'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/command/commander.rb:38:in `run'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/command/commander.rb:19:in `safe_run'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/bin/i18n-tasks:41:in `block (3 levels) in <top (required)>'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/slop_command.rb:19:in `call'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/lib/i18n/tasks/slop_command.rb:19:in `block (3 levels) in slop_command'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/gems/i18n-tasks-0.7.10/bin/i18n-tasks:32:in `<top (required)>'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/bin/i18n-tasks:23:in `load'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/bin/i18n-tasks:23:in `<main>'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/sangwoojoo/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by bartimaeus** [comment]
@joowh85 take a look at this other issue https://github.com/glebm/i18n-tasks/issues/66#issuecomment-45410459. You may have reached your limit for the day.

Or you may need to enable the [Translate API](https://cloud.google.com/translate/v2/faq#technical) for your [application] (https://console.developers.google.com)

**Comment by bartimaeus** [comment]
Try passing in the language you wish to translate and see if you get the same error  `i18n-tasks translate-missing --from base es`.

I ended up running this command a lot so I made a bash alias
```bash
alias translate='bundle exec i18n-tasks translate-missing --from base $@'
```
so that I only have to type the language(s) I want to translate. e.g., `translate es` or `translate es it pt`

**Comment by joowh85** [comment]
Thanks @bartimaeus

**Comment by joefarish** [comment]
I was able to get translate-missing to work by adding billing details on the developer console (there is currently a free $300 to spend in 60 days offer). Looking at the developer console my earlier requests were returning a Client error (4xx). 

The original i18n-tasks error message I was getting is below:

```
/Users/joefarish/.rvm/gems/ruby-2.1.1@blue-rails/gems/i18n-tasks-0.7.12/lib/i18n/tasks/google_translation.rb:90:in `next': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by j540** [comment]
I was also getting this error, and found that it was a rate limit. To resolve it I waited 100 seconds between translating to each individual language.

**Comment by viktorsmari** [comment]
I am also still having this issue.
I am using `google_translate_api_key` 

If I list all my languages manually it works.

Always works, never errors:
`be i18n-tasks translate-missing -l es fr it nl no pt de da is`

Never works, always errors:
`be i18n-tasks translate-missing`

If it was a rate limiting issue I guess it would sometimes error when I call it with my list using `-l`

When I call it without the `-l` is it trying to translate all languages in the world?

Does `translate-missing` not check my list of `i18n.available_languages`? I have ~9 languages.

**Comment by davidwessman** [comment]
@viktorsmari Does it crash if you include `en-GB` in your language list as well?

**Comment by viktorsmari** [comment]
@davidwessman it does **not** error if I do this:
`i18n-tasks translate-missing -l da de es fr is it nl no pt sv en-GB`
