### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by jvenezia** [glebm/i18n-tasks#146]
Hi,

I get an encoding issue since I tried to upgrade from *0.7.10* to *0.7.13* : 

```
> i18n-tasks health
Forest (en, fr) has 1150 keys across 2 locales. On average, values are 101 characters long, keys have 3.5 segments, a locale has 575 keys.
/Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/scanners/pattern_scanner.rb:14:in `scan': invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/scanners/pattern_scanner.rb:14:in `scan_file'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/scanners/base_scanner.rb:54:in `block in keys'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/scanners/base_scanner.rb:89:in `block in traverse_files'
	from /Users/jeremyvenezia/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/find.rb:48:in `block (2 levels) in find'
	from /Users/jeremyvenezia/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/find.rb:47:in `catch'
	from /Users/jeremyvenezia/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/find.rb:47:in `block in find'
	from /Users/jeremyvenezia/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/find.rb:42:in `each'
	from /Users/jeremyvenezia/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/find.rb:42:in `find'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/scanners/base_scanner.rb:81:in `traverse_files'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/scanners/base_scanner.rb:53:in `keys'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/used_keys.rb:17:in `used_tree'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/missing_keys.rb:83:in `missing_used_tree'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/missing_keys.rb:53:in `missing_used_forest'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/missing_keys.rb:25:in `block in missing_keys'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/missing_keys.rb:24:in `each'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/missing_keys.rb:24:in `inject'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/missing_keys.rb:24:in `missing_keys'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/command/commands/missing.rb:19:in `missing'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/command/commands/health.rb:19:in `health'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/command/commander.rb:38:in `run'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/command/commander.rb:19:in `safe_run'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/bin/i18n-tasks:41:in `block (3 levels) in <top (required)>'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/slop_command.rb:19:in `call'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/lib/i18n/tasks/slop_command.rb:19:in `block (3 levels) in slop_command'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/gems/i18n-tasks-0.7.13/bin/i18n-tasks:32:in `<top (required)>'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/bin/i18n-tasks:23:in `load'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/bin/i18n-tasks:23:in `<main>'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jeremyvenezia/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

Any Idea ?

**Comment by glebm** [comment]
Please try upgrading to 0.8.3

**Comment by jvenezia** [comment]
Works great with 0.8.5 , sorry for the delay!
