### ISSUE TITLE
Default config not containing expected key

### ISSUE THREAD

**Issue by smokinjoe** [glebm/i18n-tasks#157]
Howdy!

So I'm looking to clean out my localizations and really believe this gem should do the trick.  A problem I've run into however, has me at a dead end:

After installing the gem, `cp`ing the config and making some modifications I'm left with this i18n-tasks.yml file:

````
base_locale: en
data:
  yaml:
    write:
      line_width: -1
search:
   relative_roots:
     - app/views
     - app/controllers
     - app/helpers
     - app/presenters
  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/audios
````

Unfortunately, when I attempt to perform the task `i18n-tasks unused` I'm getting this error:

````
/Users/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
  from /Users/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
  from /Users/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
  from /Users/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/configuration.rb:16:in `file_config'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/configuration.rb:30:in `config='
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/base_task.rb:38:in `initialize'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:58:in `new'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:58:in `base_task'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:48:in `commands'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:110:in `parse_command!'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:62:in `parse!'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:38:in `run'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:18:in `block in start'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:199:in `auto_output_coloring'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:16:in `start'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/lib/i18n/tasks/cli.rb:9:in `start'
  from /Users/me/.rvm/gems/ruby-2.2.1/gems/i18n-tasks-0.8.5/bin/i18n-tasks:13:in `<top (required)>'
  from /Users/me/.rvm/gems/ruby-2.2.1/bin/i18n-tasks:23:in `load'
  from /Users/me/.rvm/gems/ruby-2.2.1/bin/i18n-tasks:23:in `<main>'
  from /Users/me/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
  from /Users/me/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

My rough experience has me guestimating that the issue lies in my config yml file, but I'm lost in trying to find examples of other people's configs to maybe compare why my `base_locale` key is causing issues.

**Comment by smokinjoe** [comment]
Turns out it was a PEBCAK issue!

I didn't actually *need* to turn on `relative_roots` and instead excluded a problem file!
