### ISSUE TITLE
Add specs for checking for untranslated resource names and attributes

### ISSUE THREAD

**Issue by jmuheim** [glebm/i18n-tasks#183]
I have created this (pretty ugly) spec file with checks for untranslated resource names and attributes:

``` ruby
require 'rails_helper'
require 'i18n/tasks'

describe 'I18n' do
  it 'does not have missing model attribute translations' do
    I18n.backend.send(:init_translations)
    fail_message = ''
    options = YAML.load_file(Rails.root.to_s + '/config/i18n-tasks.yml')

    I18n.available_locales.each do |locale|
      I18n.locale = locale

      project_models.each do |model|
        missing_columns = []
        model_attributes_to_ignore = options['ignore_models']['attributes'][model.name.underscore] || []

        model.column_names.reject do |column_name|
          column_name =~ /^id$|_id$/
        end.each do |column_name|
          begin
            I18n.t "activerecord.attributes.#{model.name.underscore}.#{column_name}", raise: true
          rescue I18n::MissingTranslationData => exception
            missing_columns << column_name unless model_attributes_to_ignore.include? column_name
          end
        end

        fail_message += "- #{model.name} (#{locale}): " + missing_columns.join(', ') + "\n" if missing_columns.any?
      end
    end

    fail "Missing model attribute translations:\n#{fail_message}" unless fail_message.empty?
  end

  it 'does not have missing model name translations' do
    I18n.backend.send(:init_translations)
    fail_message = ''
    model_names_to_ignore = YAML.load_file(Rails.root.to_s + '/config/i18n-tasks.yml')['ignore_models']['names']

    I18n.available_locales.each do |locale|
      project_models.each do |model|
        model_key = "activerecord.models.#{model.name.underscore.to_sym}"

        begin
          I18n.backend.send(:translations)[locale][:activerecord][:models][model.name.underscore.to_sym][:one]
        rescue NoMethodError
          fail_message += "- #{model.name} (#{locale}): #{model_key}.one\n" unless model_names_to_ignore.include? model.name.underscore
        end

        begin
          I18n.backend.send(:translations)[locale][:activerecord][:models][model.name.underscore.to_sym][:other]
        rescue NoMethodError
          fail_message += "- #{model.name} (#{locale}): #{model_key}.other\n" unless model_names_to_ignore.include? model.name.underscore
        end
      end
    end

    fail "Missing model name translations:\n#{fail_message}" unless fail_message.empty?
  end

  def project_models
    @project_models ||= ::ActiveRecord::Base.subclasses.collect { |type| type.name }.reject { |descendant| descendant =~ /^HABTM_|ActiveRecord|PaperTrail/ }.sort.map { |descendant| descendant.constantize }
  end
end
```

It can be configured in the `i18n-tasks.yml` file like this:

``` yml
ignore_models:
  names:
    - role
    - paper_trail/version
  attributes:
    user:
      - encrypted_password
      - reset_password_token
      - reset_password_sent_at
      - remember_created_at
      - unconfirmed_email
      - confirmation_token
      - confirmation_sent_at
      - unlock_token
      - sign_in_count
      - lock_version
```

It results in something like this:

```
Failures:

  1) I18n does not have missing model attribute translations
     Failure/Error: fail "Missing model attribute translations:\n#{fail_message}" unless fail_message.empty?
     RuntimeError:
       Missing model attribute translations:
       - User (de): unconfirmed_email
       - User (en): unconfirmed_email
     # ./spec/i18n_keys_spec.rb:31:in `block (2 levels) in <top (required)>'

  2) I18n does not have missing model name translations
     Failure/Error: fail "Missing model name translations:\n#{fail_message}" unless fail_message.empty?
     RuntimeError:
       Missing model name translations:
       - Role (de): activerecord.models.role.one
       - Role (de): activerecord.models.role.other
       - Role (en): activerecord.models.role.one
       - Role (en): activerecord.models.role.other
     # ./spec/i18n_keys_spec.rb:57:in `block (2 levels) in <top (required)>'
```

Maybe this could be added to the gem's `i18n_spec.rb`?

**Comment by glebm** [comment]
This would make sense as a separate scanner, so that tasks such as add-missing work on it. Probably would be best to package this as a gem.

**Comment by neckhair** [comment]
Exactly what I was looking for @jmuheim :smile:

**Comment by jmuheim** [comment]
:laughing: Don't hesitate to prettify my ugly code. And I have the feeling that's a bit buggy sometimes, but it served me quite well (and still does).
