### ISSUE TITLE
Missing `bold` method when running `i18n-tasks irb`

### ISSUE THREAD

**Issue by tspangler** [glebm/i18n-tasks#222]
When attempting to run `i18n-tasks irb`, I get the following error:

`/Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/console_context.rb:34:in `banner': undefined method `bold' for I18n::Tasks::ConsoleContext::Messages:Module (NoMethodError)`

It appears that the `rake` tasks aren't requiring `term/ansicolor` properly. I've verified that I have all dependencies installed.

Here's the remainder of the trace:

```
from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/console_context.rb:22:in `start'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/command/commands/meta.rb:31:in `irb'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/command/commander.rb:23:in `run'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/cli.rb:40:in `block in run'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/cli.rb:38:in `run'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/cli.rb:18:in `block in start'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/cli.rb:202:in `auto_output_coloring'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/cli.rb:16:in `start'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/lib/i18n/tasks/cli.rb:10:in `start'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/gems/i18n-tasks-0.9.9/bin/i18n-tasks:17:in `<top (required)>'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/bin/i18n-tasks:22:in `load'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/bin/i18n-tasks:22:in `<main>'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/timothy/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by glebm** [comment]
Good catch! Fixed and release v0.9.10
