### ISSUE TITLE
i18n-tasks add-missing behaves strangely if keys are "null"

### ISSUE THREAD

**Issue by garrettgsb** [glebm/i18n-tasks#225]
We have a one-line helper script that generates a pseudo-locale file that looks like this:

```
i18n-tasks add-missing -v '☃ %{value}' snowman
```

It was producing the following error:

```
`sort': comparison of I18n::Tasks::Data::Tree::Node with I18n::Tasks::Data::Tree::Node failed (ArgumentError)
```

After some sleuthing, we found that one of the files had a key, representing an empty string, that was called `null`. That seemed fishy, and sure enough, when we changed it to `noop`, `i18n-tasks add-missing` began working right away.

Further experimentation revealed that this is reproducible elsewhere in the project. It should be noted that keys called `null` also cause the i18n gem itself to return a "missing translation error," but perhaps the user could be notified of the problem with a more descriptive error/warning.

Full stack trace below.

```
/Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:36:in `sort': comparison of I18n::Tasks::Data::Tree::Node with I18n::Tasks::Data::Tree::Node failed (ArgumentError)
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:36:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/node.rb:143:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `block in to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `map'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/node.rb:143:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `block in to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `map'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/node.rb:143:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `block in to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `map'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/node.rb:143:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `block in to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `map'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:39:in `to_hash'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/file_formats.rb:41:in `write_tree'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/file_system_base.rb:49:in `block in set'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/router/pattern_router.rb:43:in `block in route'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/router/pattern_router.rb:42:in `each'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/router/pattern_router.rb:42:in `route'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/file_system_base.rb:48:in `set'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/file_system_base.rb:63:in `block in merge!'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:16:in `each'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/tree/nodes.rb:16:in `each'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/file_system_base.rb:60:in `inject'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/data/file_system_base.rb:60:in `merge!'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/command/commands/missing.rb:65:in `add_missing'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/command/commander.rb:26:in `run'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/cli.rb:44:in `run'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/cli.rb:20:in `block (2 levels) in start'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/cli.rb:205:in `auto_output_coloring'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/cli.rb:18:in `block in start'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/cli.rb:17:in `start'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/lib/i18n/tasks/cli.rb:10:in `start'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/gems/i18n-tasks-0.9.6/bin/i18n-tasks:16:in `<top (required)>'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/bin/i18n-tasks:23:in `load'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/bin/i18n-tasks:23:in `<main>'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gsb/.rvm/gems/ruby-2.3.1@contractually/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by glebm** [comment]
@garrettgsb I've added a warning in the commit above.
