### ISSUE TITLE
Server doesn't start after installing gem

### ISSUE THREAD

**Issue by joshuadelange** [glebm/i18n-tasks#276]
Hello there,

Thanks for creating what looks like a great gem. I have on issue I can't wrap my head around though, and I'm wondering wether it may be a bug?

After running bundle install, I try to boot up the server and with or without any configuration I get the following errors:

```
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.9-compliant syntax, but you are running 2.2.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> Booting Puma
=> Rails 5.0.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
/Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/haml-5.0.1/lib/haml/helpers/safe_erubi_template.rb:5: warning: toplevel constant Erubi referenced by ActionView::Template::Handlers::ERB::Erubi
Exiting
/Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/haml-5.0.1/lib/haml/helpers/safe_erubi_template.rb:5:in `<module:Haml>': superclass must be a Class (Module given) (TypeError)
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/haml-5.0.1/lib/haml/helpers/safe_erubi_template.rb:4:in `<top (required)>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/haml-5.0.1/lib/haml/railtie.rb:30:in `block (2 levels) in <class:Railtie>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/lazy_load_hooks.rb:43:in `instance_eval'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/lazy_load_hooks.rb:49:in `each'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.4/lib/action_view/base.rb:215:in `<class:Base>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.4/lib/action_view/base.rb:139:in `<module:ActionView>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.4/lib/action_view/base.rb:10:in `<top (required)>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:5:in `<top (required)>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/web-console-3.5.1/lib/web_console/extensions.rb:24:in `<module:ActionDispatch>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/web-console-3.5.1/lib/web_console/extensions.rb:23:in `<top (required)>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/web-console-3.5.1/lib/web_console/railtie.rb:10:in `block in <class:Railtie>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `run'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/joshuadelange/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/application.rb:352:in `initialize!'
	from /Users/joshuadelange/Projects/donationbox/config/environment.rb:5:in `<top (required)>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/joshuadelange/Projects/donationbox/config.ru:3:in `block in <main>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from /Users/joshuadelange/Projects/donationbox/config.ru:in `new'
	from /Users/joshuadelange/Projects/donationbox/config.ru:in `<main>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/commands/server.rb:84:in `app'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/commands/server.rb:148:in `log_to_stdout'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/commands/server.rb:102:in `start'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/joshuadelange/Projects/donationbox/bin/rails:9:in `require'
	from /Users/joshuadelange/Projects/donationbox/bin/rails:9:in `<top (required)>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /Users/joshuadelange/.rvm/gems/ruby-2.2.3/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/joshuadelange/Projects/donationbox/bin/spring:13:in `require'
	from /Users/joshuadelange/Projects/donationbox/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

Condensed gemfile: 

```
gem 'rails',  '~> 5.0.0'
gem 'pg', '~> 0.18'
gem 'puma'
gem 'haml'
gem 'haml-rails'
gem 'trix'


# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

group :development, :test do
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 3.0'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'letter_opener'
  gem 'i18n-tasks', '~> 0.9.20'
end

group :production do
  gem 'rails_12factor'
end

ruby "2.2.3"
```

Do you guys know what the issue might be?

Thank you for any help you might be able to give!

**Comment by glebm** [comment]
It's a bug in Haml, fixed in v5.0.3. Run `bundle update haml`.
https://github.com/haml/haml/pull/952
