### ISSUE TITLE
Not work with i18n from v1.14.3

### ISSUE THREAD

**Issue by wongyouth** [glebm/i18n-tasks#559]
When run `i18n-tasks tree-set-value -h`

Got error

```
i18n-tasks tree-set-value hello
bundler: failed to load command: i18n-tasks (/Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/bin/i18n-tasks)
#StandWithUkraine
/Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n/backend/base.rb:65:in `translate': reserved key :default used in "Value. Interpolates: %{value}, %{human_key}, %{key}, %{default}, %{value_or_human_key}, %{value_or_default_or_human_key}" (I18n::ReservedInterpolationKey)

          raise ReservedInterpolationKey.new($1.to_sym, entry)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n.rb:363:in `block in translate_key'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n.rb:362:in `catch'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n.rb:362:in `translate_key'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n.rb:222:in `translate'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/command/dsl.rb:46:in `block in t'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:188:in `try_call'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:155:in `block in optparse_args'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:155:in `map!'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:155:in `optparse_args'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:92:in `block (2 levels) in optparse_command!'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:91:in `each'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:91:in `block in optparse_command!'
	from /nix/store/zqn7fqywg11qjh5w3a9q6wki8spx73pv-ruby-3.2.2/lib/ruby/3.2.0/optparse.rb:1153:in `initialize'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:90:in `new'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:90:in `optparse_command!'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:80:in `optparse!'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:73:in `parse!'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:50:in `block in run'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n.rb:322:in `with_locale'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:49:in `run'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:18:in `block in start'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:211:in `auto_output_coloring'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:17:in `start'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/lib/i18n/tasks/cli.rb:11:in `start'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/i18n-tasks-1.0.13/bin/i18n-tasks:15:in `<top (required)>'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/bin/i18n-tasks:25:in `load'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/bin/i18n-tasks:25:in `<top (required)>'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/ryan/code/foo/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
	from /nix/store/dqazkqhx0v10pihvf7vgcfaf71aqs51d-devenv-profile/bin/bundle:25:in `load'
	from /nix/store/dqazkqhx0v10pihvf7vgcfaf71aqs51d-devenv-profile/bin/bundle:25:in `<main>'

```

**Version:**

- i18n: v1.14.3, v1.14.4
- i18n-tasks: v1.0.13

I found this is related with the PR https://github.com/ruby-i18n/i18n/pull/678

**Comment by wongyouth** [comment]
Close for duplication with https://github.com/glebm/i18n-tasks/issues/552
